### ISSUE TITLE
同一门课在一周内多次上课在ical中只会有一个记录

### ISSUE THREAD

**Issue by onecoconutcoder** [longzhenren/buaa-gsmis-ical#2]
如标题所示

**Comment by longzhenren** [comment]
烦请提供“我的课程app”页面截图及HTML代码。

**Comment by onecoconutcoder** [comment]
这里只会解析出一个
![WechatIMG262](https://github.com/longzhenren/buaa-gsmis-ical/assets/58937487/4794a412-0938-4f79-89b3-9ee60d7e75c4)

**Comment by longzhenren** [comment]
pr merged #3
